<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ConsoleTest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HoldemPoker.Evaluator" Version="1.0.1" />
  </ItemGroup>

</Project>
